---
- name: install rsyslog
  apt:
    state: present
    pkg:
    - rsyslog
  notify: Restart and Enable rsyslog

- name: show variables per host
  debug:
    var: is_log_server

- name: Copy Server Config File
  template:
    src: server.conf
    dest: /etc/rsyslog.conf
    force: yes
  when: is_log_server
  notify: Restart and Enable rsyslog

- name: Copy Client Config File
  template:
    src: client.conf
    dest: /etc/rsyslog.conf
    force: yes
  when: not is_log_server
  notify: Restart and Enable rsyslog
