---
- name: Download Ubuntu cloud image #does not appear to re-download if the file already exists
  get_url:
    url: "{{ image_url }}"
    dest: "/tmp/{{ image_tgt }}"
- name: Create .vhdx file from cloud image
  command:
    argv:
      - qemu-img
      - convert
      - "/tmp/{{ image_tgt }}"
      - "-O"
      - "vhdx"
      - "{{ vhd_dir }}{{ vm_id }}-os2.vhdx"
