---
- name: Download Ubuntu cloud image #does not appear to re-download if the file already exists
  get_url:
    url: "{{ image_url }}"
    dest: "/tmp/{{ image_tgt }}"
- name: Create .vhdx file from cloud image
  command:
    argv:
      - qemu-img
      - convert
      - "/tmp/{{ image_tgt }}"
      - "-O"
      - "vhdx"
      - "{{ vhd_dir }}{{ vm_id }}-os2.vhdx"
- name: Create user data file
  template:
    src: user-data.j2
    dest: "/tmp/user-data{{ vm_id }}"
- name: Create meta data file
  template:
    src: meta-data.j2  #KLUDGE - the meta-data.j2 template asumes alot about the networking environment!
    dest: "/tmp/meta-data{{ vm_id }}"
- name: Create .iso seed file from meta data and user data
  command:
    argv:
      - cloud-localds
      - "{{ vhd_dir }}{{ vm_id }}-seed2.iso"
      - "/tmp/user-data{{ vm_id }}"
      - "/tmp/meta-data{{ vm_id }}"
- name: Create PowerShell script
  template:
    src: CreateVm.ps1.j2
    dest: "/tmp/create-vm{{ vm_id }}.ps1"