---
- name: Print something passed as a role parameter
  debug:
    var: vm
- name: Print dynamic vars
  debug:
    var: user_data_file
- name: Download Ubuntu cloud image #does not appear to re-download if the file already exists
  get_url:
    url: "{{ image_url }}"
    dest: "/tmp/{{ image_tgt }}"
- name: Create .vhdx file from cloud image
  command:
    argv:
      - qemu-img
      - convert
      - "/tmp/{{ image_tgt }}"
      - "-O"
      - "vhdx"
      - "{{ vhd_dir }}{{ vhdx_file }}"
- name: Create user data file
  template:
    src: user-data.j2
    dest: "/tmp/{{ user_data_file }}"
- name: Create meta data file
  template:
    src: meta-data.j2 # assumes interface name is eth0
    dest: "/tmp/{{ meta_data_file }}"
- name: Create .iso seed file from meta data and user data
  command:
    argv:
      - cloud-localds
      - "{{ vhd_dir }}{{ seed_file }}"
      - "/tmp/{{ user_data_file }}"
      - "/tmp/{{ meta_data_file }}"
- name: Create PowerShell script to destroy VM
  template:
    src: DestroyVm.ps1.j2
    dest: "{{ vhd_dir }}{{ pshell_destroy_file }}"
- name: Create PowerShell script to create and start VM
  template:
    src: CreateVm.ps1.j2
    dest: "/tmp/{{ pshell_create_file }}"
- name: Run script to create and start VM
  command:
    argv:
      - "powershell.exe"
      - "/tmp/{{ pshell_create_file }}"
