---
api_user: root@pam
cpu_type: host

ethports:
  net0: "virtio,bridge={{ netenv.dmz.vbridge }}"
netconfig:
  ipconfig0: "ip={{ ansible_host }}/{{ netenv.dmz.mask }},gw={{ netenv.dmz.gw }}"
dns_srv:
  - "{{ netenv.dmz.dns }}"
