---
addtl_space: 8G
vcpus: 4
ram: 4096
vram: 32

dotnet_packages:
  - dotnet-sdk-2.1
  - dotnet-sdk-6.0

# This VM is special because it has an
#   IP on the LAN network
#   AND on the DMZ network.
# this allows it to act as an ansible host to run commands
# and do SSH on both bare-metal servers and also vms
ethports:
  net0: "virtio,bridge={{ netenv.lan.vbridge }}"
  net1: "virtio,bridge={{ netenv.dmz.vbridge }}"
netconfig:
  ipconfig0: "ip={{ ansible_host }}/{{ netenv.lan.mask }},gw={{ netenv.lan.gw }}"
  ipconfig1: "ip={{ secondary_ip }}/{{ netenv.dmz.mask }}"
dns_srv: "{{ netenv.lan.dns }}" # override the default in vms-provision
