---
- name: Update cache and upgrade existing packages
  apt:
    upgrade: full
    cache_valid_time: 3600
  register: apt_result
- name: Restart system if required any packages were installed or upgraded
  reboot:
  when: apt_result['changed']
  
