---
- name: Add the unprivileged user.
  hosts: ucloud
  become: yes
  tasks:
  - name: Add the user vince.
    user:
      name: vince
      comment: Vincent Saelzler
      # will ultimately transition to using ansible vault
      # for now, setting placeholder
      # https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
      # ansible all -i localhost, -m debug -a 'msg={{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}'
      password: '$6$mysecretsalt$qJbapG68nyRab3gxvKWPUcs2g3t0oMHSHMnSKecYNpSi3CuZm.GbBqXO8BE6EI6P1JUefhA0qvD7b5LSh./PU1'
      shell: /bin/bash
  - name: Set public keys.
    authorized_key:
      user: vince
      state: present
      key: '{{ item }}'
    with_file:
      - '/mnt/c/Users/vince/.ssh/id_rsa.pub' # windows powershell
      - '~/.ssh/id_rsa.pub' # WSL
