--- 
all: 
  children:

    # primary groups (based on physical machine)
    proxmox_nodes:
      hosts:
        # pve2:
        #   ansible_host: 192.168.128.2
        #   secondary_ip: 192.168.129.2
        # pve3:
        #   ansible_host: 192.168.128.3
        #   secondary_ip: 192.168.129.3
        pve4:
          ansible_host: 192.168.128.4
          secondary_ip: 192.168.129.4
        pve5:
          ansible_host: 192.168.128.5
          secondary_ip: 192.168.129.5
    proxmox_svcs:
      children:
        node4:
          hosts:
            # ethereum:
            #   ansible_host: 192.168.129.102
            # bitcoin:
            #   ansible_host: 192.168.129.101
            devenv:
              ansible_host: 192.168.128.60
              secondary_ip: 192.168.129.60
            proxy:
              ansible_host: 192.168.129.30
        node5:
          hosts:
            service1:
              ansible_host: 192.168.129.71
            service2:
              ansible_host: 192.168.129.72
        #     robox:
        #       ansible_host: 192.168.129.100

    # container or VM
    proxmox_vms:
      hosts:
        devenv:
    proxmox_cts:
      hosts:
        proxy:
        service1:
        service2:

    # installed OS (for VMs - all containers use Debian)
    centos_cloud:
      hosts:
        robox:
    ubuntu_cloud:
      hosts:
        ethereum:
        bitcoin:
        devenv:
