--- 
all: 
  children:
    # primary groups (based on physical machine)
    proxmox_nodes:
      hosts:
        pve2:
          ansible_host: 192.168.128.2
        pve3:
          ansible_host: 192.168.128.3
        pve4:
          ansible_host: 192.168.128.4
        pve5:
          ansible_host: 192.168.128.5
    proxmox_vms:
      children:
        node2:
          hosts:
            ethereum:
              ansible_host: 192.168.129.102
            bitcoin:
              ansible_host: 192.168.129.101
            dotnet:
              ansible_host: 192.168.129.100
        node5:
          hosts:
            robox:
              ansible_host: 192.168.129.100
    # secondary groups
    centos_cloud:
      hosts:
        robox:
    ubuntu_cloud:
      hosts:
        ethereum:
        bitcoin:
        dotnet:
