--- 
all: 
  children:
    # primary groups (include network config here)
    virtual:
      hosts:
        dotnet:
          ansible_host: 192.168.1.27
        bitcoin:
          ansible_host: 192.168.1.28
        polkadot:
          ansible_host: 192.168.1.29
        ethereum:
          ansible_host: 192.168.1.30
    virt_servers:
      hosts:
        hyper_v:
          ansible_host: localhost
          ansible_connection: local
    proxmox_nodes:
      hosts:
        # pve2:
        #   ansible_host: 192.168.128.2
        # pve3:
        #   ansible_host: 192.168.128.3
        pve4:
          ansible_host: 192.168.128.4
        pve5:
          ansible_host: 192.168.128.5
    routers:
      hosts:
        pfsense1:
          ansible_host: 192.168.128.1
    # secondary groups
    ubuntu_cloud:
      hosts:
        bitcoin:
        dotnet:
        polkadot:
        ethereum:
