--- 
all: 
  children:
    # primary groups (based on physical machine)
    proxmox_nodes:
      hosts:
        # pve2:
        #   ansible_host: 192.168.128.2
        #   secondary_ip: 192.168.129.2
        # pve3:
        #   ansible_host: 192.168.128.3
        #   secondary_ip: 192.168.129.3
        pve4:
          ansible_host: 192.168.128.4
          secondary_ip: 192.168.129.4
        pve5:
          ansible_host: 192.168.128.5
          secondary_ip: 192.168.129.5
    proxmox_vms:
      children:
        node4:
          hosts:
            # ethereum:
            #   ansible_host: 192.168.129.102
            # bitcoin:
            #   ansible_host: 192.168.129.101
            devenv:
              ansible_host: 192.168.128.60
              secondary_ip: 192.168.129.60
        # node5:
        #   hosts:
        #     robox:
        #       ansible_host: 192.168.129.100
    # secondary groups
    centos_cloud:
      hosts:
        robox:
    ubuntu_cloud:
      hosts:
        ethereum:
        bitcoin:
        devenv:
