--- 
all: 
  children:
    # primary groups (include network config here)
    virtual:
      hosts:
        dotnet:
          ansible_host: 192.168.1.27
        bitcoin:
          ansible_host: 192.168.1.28
        polkadot:
          ansible_host: 192.168.1.29
        ethereum:
          ansible_host: 192.168.1.30
        docker:
          ansible_host: 192.168.1.31
    virt_servers:
      hosts:
        hyper_v:
          ansible_host: localhost
          ansible_connection: local
    # secondary groups
    ubuntu_cloud:
      hosts:
        bitcoin:
        dotnet:
        polkadot:
        ethereum:
        docker:
