--- 
all: 
  children:

    # primary groups (based on physical machine)
    proxmox_nodes:
      hosts:
        pve4:
          ansible_host: 192.168.128.4
          secondary_ip: 192.168.129.4
    proxmox_svcs:
      children:
        node4:
          hosts:
            proxy0:
              ansible_host: 192.168.129.30
            # log0:
            #   ansible_host: 192.168.129.31
            elk0:
              ansible_host: 192.168.129.32
            devenv:
              ansible_host: 192.168.128.60
              secondary_ip: 192.168.129.60
            service1:
              ansible_host: 192.168.129.71
            service2:
              ansible_host: 192.168.129.72

    # container or VM
    proxmox_vms:
      hosts:
        devenv:
    proxmox_cts:
      hosts:
        proxy0:
        log0:
        elk0:
        service1:
        service2:

    # installed OS (for VMs - all containers use Debian)
    ubuntu:
      hosts:
        devenv:
    debian:
      hosts:
        proxy0:
        log0:
        elk0:
        service1:
        service2:
