--- 
all: 
  children:

    # primary groups (based on physical machine)
    proxmox_nodes:
      hosts:
        pve4:
          ansible_host: 192.168.128.4
    proxmox_svcs:
      children:
        node4:
          hosts:
            router:
              ansible_host: 192.168.129.1
              secondary_ip: 99.107.120.140
            proxy0:
              ansible_host: 192.168.129.30
            elk0:
              ansible_host: 192.168.129.32
            devenv:
              ansible_host: 192.168.128.60
              secondary_ip: 192.168.129.60
            service1:
              ansible_host: 99.107.120.137
            service2:
              ansible_host: 192.168.129.72
            build:
              ansible_host: 192.168.129.73
            collatz:
              ansible_host: 192.168.129.74
            loancalc:
              ansible_host: 192.168.129.75

    # container or VM
    proxmox_vms:
      hosts:
        devenv:
    proxmox_cts:
      hosts:
        router:
        proxy0:
        elk0:
        service1:
        service2:
        build:
        collatz:
        loancalc:

    # installed OS (for VMs - all containers use Debian)
    ubuntu:
      hosts:
        devenv:
    debian:
      hosts:
        router:
        proxy0:
        elk0:
        service1:
        service2:
        build:
        collatz:
        loancalc:

    # run dotnet core projects
    dotnet_apps:
      hosts:
        collatz:
        loancalc:
