---
- name: Update cache and upgrade existing packages
  apt:
    upgrade: dist
    cache_valid_time: 3600
- name: Install new apt packages
  apt:
    state: present
    pkg:
      - tasksel
      - ubuntu-desktop-minimal
      - spice-vdagent
      - qemu-guest-agent
  notify:
  - restart
