---
- name: Add the user.
  user:
    name: "{{ usr_name }}"
    comment: "{{ full_name }}"
    password: "{{ user_pw | password_hash('sha512', user_pw_salt) }}"
    shell: /bin/bash
- name: Add authorized public key.
  authorized_key:
    user: "{{ usr_name }}"
    state: present
    exclusive: yes
    key: '{{ pub_key }}'
