---
- name: Add the user vince.
  user:
    name: vince
    comment: Vincent Saelzler
    password: "{{ user_pw | password_hash('sha512', user_pw_salt) }}"
    shell: /bin/bash
- name: Set public key.
  authorized_key:
    user: vince
    state: present
    exclusive: yes
    key: '{{ pub_key }}'
# there doesn't seem to be a mechanisim to set git configuration at the user scope
# these are all going into the global (system) level configuration
- name: Set gitconfig user
  git_config:
    name: user.name
    value: 'Vincent Saelzler'
- name: Set gitconfig email
  git_config:
    name: user.email
    value: 'vincent.saelzler@gmail.com'
