image_url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
image_tgt: focal.img
vhd_dir: "/mnt/c/Users/Public/Documents/Hyper-V/Virtual hard disks/" #this is the default location for Hyper-V