---
- name: Install extensions to VS Code
  command:
    cmd: |
      code --install-extension ms-dotnettools.csharp
      code --install-extension ionide.ionide-fsharp
      code --install-extension oderwat.indent-rainbow
      code --install-extension ms-mssql.mssql 	
    # cmd: whoami
