--- 
all: 
  children: 
    ucloud: 
      hosts: "192.168.1.27"
      vars: 
        ansible_user: ubuntu
    vagrantboxes: 
      hosts: 
        localhost: 
          ansible_port: 2222
          ansible_private_key_file: .vagrant/machines/default/virtualbox/private_key
      vars: 
        ansible_user: vagrant
