---
- name: Download Microsoft's Ubuntu 20.04 deb File
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: '/tmp'

- name: Make MS Packages Available for Install
  apt:
    deb: '/tmp/packages-microsoft-prod.deb'

- name: Install New apt Packages.
  apt:
    state: present
    update_cache: yes # important
    pkg: dotnet-sdk-6.0
  notify: Restart
