---
# networking environment
netenv:
  lan:
    mask: 24
    gw: 192.168.128.1
    dns: 192.168.128.1
    vbridge: vmbr0
  dmz:
    mask: 24
    gw: 192.168.129.1
    dns: 192.168.129.1
    vbridge: vmbr1
  wan:
    mask: 29
    gw: 99.107.120.142
    vbridge: vmbr2

public_dns_servers: "1.1.1.1,8.8.8.8" #cloudflare and google

# domains that these services are for
domains: 
  # - quercusphellos.online
  - saelzler.org
  - collatz.saelzler.org

# the certbot role expects a list of ~certificates~
# each certificate could have one or more domains
# CANNOT USE MULTIPLE DOMAINS ON ONE CERT FOR NOW
# TASK [Create symbolic links for intermediate certificate chains]
# fails
certs:
  # - domains:
    # - quercusphellos.online
  - domains:
    - saelzler.org
  - domains:
    - collatz.saelzler.org

# rsyslog and nut server (pfSense)
log_server: "192.168.129.32"
ups_server: "192.168.128.1"
ups_name: "old-smart-1500"
ups_user: upsmon_remote

# assumptions about physical location
time_zone: "America/New_York"

# assumptions about the person running all this
usr_name: "vince"
full_name: "Vincent Saelzler"
usr_email: "vincent.saelzler@gmail.com"

# the private keys need to exist on the machine that ansible is runnning on
# also will need to exist on the machine that the user plans to use for SSH access
# if the private key is lost, it's possible to recover by logging in with UN/PW and changing the public keys
# however, that would be monumentally inconvenient

# this is MY public key.
# SWAP THIS OUT IF YOU ARE NOT ME.
pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCW4Cf2kYGSvvx+HYcxs3dy4LGZ5At4+7out4usw0xY+lKlbMI5Y+tn62//3uCgDJ7zwMpq9gLOVdQ3XXdtri9e1DWIpytv26BR/RQOfslXeRw+GhVqMYsSd1Y5i9AqvDhSZN1zOA/Gq7EdGT7EGAuPfX+iehAhFXOWDOpIzWyFunMWDinYwrKesYwqLtfVREMa+8GWIijN8usGs9i4ZSdtrUDv7Lgyn9AAfpNiGu+QicYVkTbsXUwSjVmCNggX50qZvp4KuUUq5vStm5RQCRkB07fJQxR3StqMGikK60gSyWRXPxLsFsglet2WmA/4y7sGPlI3WPCFJYFM2VESVo8EMsssKAuo20MrCC8Fs2hcCpqPyBI4Las8drZ8WcWNf5Vht8FFBq7KvFySIyrvv5tD6nWok7tL3PGkDsamTAMdVTxbxLkAowo/ta31jWk3sdRHwyi8B2JrlbdGoTA73E3yhMOOA5UWbd2Si+Ykk6vwFXdzO2y7UR8ChjCiXE/U6JE= vince@RYZEN-WSL"

# credentials
# if the PWs here are not stored externally, and the ansible vault PW is lost,
# THERE IS NO WAY TO RECOVER!!
root_pw:  "{{ vault_root_pw }}"
user_pw: "{{ vault_user_pw }}"
user_pw_salt: "{{ vault_user_pw_salt }}"
ups_pw: "{{ vault_ups_pw }}"
