---
- name: Download Microsoft's Product Deb File
  get_url:
    url: "{{ dotnet_deb_file }}"
    dest: '/tmp'

- name: Make MS Packages Available for Install
  apt:
    deb: '/tmp/packages-microsoft-prod.deb'

- name: Install New apt Packages.
  apt:
    state: present
    update_cache: yes # important
    pkg: "{{ dotnet_packages }}"
  notify: Restart
