---
- name: Download Microsoft's VS Code deb File
  get_url:
    url: https://go.microsoft.com/fwlink/?LinkID=760868
    dest: '/tmp/vscode.deb'

- name: Install VS Code
  apt:
    deb: '/tmp/vscode.deb'
  notify: Restart

# - name: Install New apt Packages.
#   apt:
#     state: present
#     update_cache: yes # important
#     pkg: code
