---
- name: Download Microsoft's VS Code deb File
  get_url:
    url: https://go.microsoft.com/fwlink/?LinkID=760868
    dest: '/tmp/vscode.deb'

- name: Make VS Code Package Available for Install
  apt:
    deb: '/tmp/vscode.deb'

- name: Install New apt Packages.
  apt:
    state: present
    update_cache: yes # important
    pkg: code
  notify: Restart
