---
- name: Bootstrap Host, Including GUI and IDE
  hosts: devenv
  become: yes
  roles:
    - full-upgrade
    - personalize
    - unprivileged-user
    - ubuntu-gui
    - vs-code
    - dotnet-sdk
    - ssh-conf
    - git-conf
  handlers:
    - import_tasks: handlers/main.yml
  tasks:

  - name: Configure Ansible PPA
    apt_repository:
      repo: 'ppa:ansible/ansible'
      state: present

  - name: Install apt Packages
    apt:
      state: present
      update_cache: yes # important
      pkg:
        - ansible
        - python3-pip
        - sshpass # required to bootstrap bare-metal nodes

  - name: Hard-Code Hosts on DMZ
    lineinfile:
      path: /etc/cloud/templates/hosts.debian.tmpl
      line: "192.168.129.30 {{ item }}"
      state: present
    loop: "{{ domains }}"
    notify:
    - Restart

- name: User Config - IDE Extensions, Python Packages, Ansible Roles, and Aliases
  hosts: devenv
  vars:
    ansible_user: "{{ usr_name }}"
  roles:
    - vs-code-ext
    - private-key
    - vault-pw
    - aliases
  tasks:

  - name: Install Certbot Role from Ansible Galaxy
    community.general.ansible_galaxy_install:
      type: role
      name: geerlingguy.certbot

  - name: Install Python Packages
    pip:
      name:
      - proxmoxer

  - name: Clone This Repository
    git:
      repo: 'https://github.com/VincentSaelzler/hyper-homelab.git'
      dest: "~/src/hyper-homelab/"
