---
- name: Install Packages
  hosts: elk0
  become: yes
  handlers:
    - import_tasks: handlers/main.yml
  # roles:
  #   - full-upgrade
  #   - personalize
  #   - unprivileged-user
  tasks:
  - name: Install apt packages
    apt:
      state: present
      pkg:
      - gpg
  - name: Add apt Signing Key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  - name: Configure Elastic Archive
    apt_repository:
      repo: 'deb https://artifacts.elastic.co/packages/8.x/apt stable main'
      state: present
  - name: Install apt packages
    apt:
      state: present
      pkg:
      - elasticsearch
    # - name: Restart rsyslog service
    #   systemd:
    #     name: rsyslog
    #     state: restarted
    #     enabled: yes