---
- name: Bootstrap, Including Dotnet SDK(s)
  hosts: build0
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - full-upgrade
    - personalize
    - rsyslog
    - dotnet
    - unprivileged-user
  tasks:
    - name: Install Git
      apt:
        pkg: git
