---
- name: Install MS SQL Server
  hosts: mssql
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - full-upgrade
    - personalize
    - rsyslog
    - unprivileged-user
  tasks:
    - name: Install GPG
      apt:
        state: present
        pkg: gpg

    - name: Add apt Signing Key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc

    - name: Register SQL Server 2019 Repository
      ansible.builtin.apt_repository:
        # contents of https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list
        repo: deb [arch=amd64,armhf,arm64] https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019 focal main

    - name: Install MS SQL Server
      apt:
        pkg: mssql-server

- name: Bootstrap MS SQL Server
  hosts: mssql
  tasks:
    - name: Collect Facts About System Services
      service_facts:

    - name: Run Bootstrap Script
      command:
        cmd: /opt/mssql/bin/mssql-conf --noprompt setup
      environment:
        MSSQL_SA_PASSWORD: "{{ mssql_pw }}" #WARNING per Ansible docs, this is passed in clear text. Is there a better way?
        MSSQL_PID: express
        ACCEPT_EULA: MEH
      when: ansible_facts.services['mssql-server.service'].state != "running"
