---
- name: Install MariaDB
  hosts: mariadb
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - full-upgrade
    - personalize
    - rsyslog
    - unprivileged-user
  tasks:
    - name: Install APT Packages
      apt:
        pkg:
        - mariadb-server
        - default-libmysqlclient-dev # required for python mysqlclient package
        - python3-pip

    - name:  Copy Configuration File
      copy:
        src: tcp-listen.cnf
        dest: /etc/mysql/mariadb.conf.d/51-tcp-listen.cnf

    - name: Install Python Packages
      pip:
        name:
        - mysqlclient

    - name: Check a var 
      mysql_variables:
        variable: bind_address
      register: dbout
    
    - debug:
        var: dbout

    - name: Create a new database with name 'bobdata'
      mysql_db:
        name: bobdata

    - name: Create bob
      mysql_user:
        name: bob
        host: 192.168.129.%
        password: 12345dd
        # priv: "'bobdata.*': 'ALL,GRANT'"
        # priv: "GRANT ALL PRIVILEGES ON 'bobdata'.*"
        priv: "bobdata.*:ALL" # it looks like not having spaces is the key. submit issue on docs page?
