---
- name: Bootstrap and Install Dotnet Packages (Runtime, SDK)
  hosts: dotnet_apps, build
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - full-upgrade
    - personalize
    - rsyslog
    - unprivileged-user
    # the install on build doesn't always work the first time
    # i think it's related to installing several sdks at once, especially the old 2.1 sdk
    # not troubleshooting to much because probably won't have 2.1 dependency much longer.
    # troubleshoot by remoting into the build container and doing dpkg -a
    - dotnet
  tasks:
    - debug:
        var: dotnet_packages

- name: Install Git on Build Server
  hosts: build
  tasks:
    - name: Install Git
      apt:
        pkg: git

- name: Copy Encrypted Private Repo Deploy Key(s) to Build Server
  hosts: dotnet_apps
  vars:
    ansible_user: "{{ usr_name }}"
  tasks:
    - name:  Copy Encrypted Private Repo Deploy Key(s)
      delegate_to: build
      copy:
        src: "vault/{{ dotnet_repo_deploy_key }}"
        dest: "~/.ssh/"
        mode: "600" # mode based on what ssh-keygen auto-generated
      when: dotnet_repo_deploy_key is defined

- name: Create Directory to Run Apps
  hosts: dotnet_apps
  tasks:
    - name: Create Folder for Executable Files
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ usr_name }}"
        group: "{{ usr_name }}"
