---
# based on https://jonatack.github.io/articles/how-to-compile-bitcoin-core-and-run-the-tests
- name: Install Bitcoin and dependencies
  hosts: bitcoin
  become: yes
  roles:
    - full-upgrade
    - personalize
    - add-user
    - ubuntu-gui
  tasks:
  - name: Install dependencies
    apt:
      pkg:
      - build-essential
      - libtool
      - autotools-dev
      - automake
      - pkg-config
      - bsdmainutils
      - python3
      - libssl-dev
      - libevent-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-chrono-dev
      - libboost-test-dev
      - libboost-thread-dev
      - libminiupnpc-dev
      - libzmq3-dev
      - libqt5gui5
      - libqt5core5a
      - libqt5dbus5
      - qttools5-dev
      - qttools5-dev-tools
      - libprotobuf-dev
      - protobuf-compiler
      - git
      - libsqlite3-dev
    register: apt_result
  - name: Restart system if required any packages were installed or upgraded
    reboot:
    when: apt_result['changed']
  - name: Copy Bitcoin service file
    template:
        src: btc.service
        dest: /etc/systemd/system
  - name: Clone Bitcoin git repo
    become_user: "{{ usr_name }}"
    git:
      repo: "https://github.com/bitcoin/bitcoin.git"
      dest: "~/bitcoin-latest"
    register: git_out
  - name: Ensure the old binary is not running
    systemd:
      name: btc
      state: stopped
    when: git_out['changed']
  - name: Run script to build Bitcoin
    become_user: "{{ usr_name }}"
    script:
      chdir: "/home/{{ usr_name }}/"
      cmd: btc-build.sh "{{ usr_name }}"
    when: git_out['changed']
- name: Copy configuration files and start program as a system service
  hosts: bitcoin
  become: yes
  tasks:
  - name: Create the container directory for bitcoin config (mode based on what bitcoind auto-generated)
    become_user: "{{ usr_name }}"
    file:
      path: "~/.bitcoin/wallets/"
      state: directory
      mode: "0755"
  - name: Copy encrypted bitcoin wallet data file (mode based on what bitcoin-cli auto-generated)
    become_user: "{{ usr_name }}"
    copy:
      src: vault/BitcoinWallet.dat
      dest: "~/.bitcoin/wallets/wallet.dat"
      mode: "600"
  - name: Start and enable bitcoin service
    systemd:
      name: btc
      state: started
      enabled: yes
