---
# based on https://jonatack.github.io/articles/how-to-compile-bitcoin-core-and-run-the-tests
- name: Install Bitcoin
  hosts: bitcoin
  become: yes
  roles:
    - full-upgrade
    - personalize
    - add-user
    - ubuntu-gui
  tasks:
  - name: Install dependencies
    apt:
      pkg:
      - build-essential
      - libtool
      - autotools-dev
      - automake
      - pkg-config
      - bsdmainutils
      - python3
      - libssl-dev
      - libevent-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-chrono-dev
      - libboost-test-dev
      - libboost-thread-dev
      - libminiupnpc-dev
      - libzmq3-dev
      - libqt5gui5
      - libqt5core5a
      - libqt5dbus5
      - qttools5-dev
      - qttools5-dev-tools
      - libprotobuf-dev
      - protobuf-compiler
      - git
      - libsqlite3-dev
  - name: Reboot system if required.
    command:
      cmd: shutdown -r now 'Rebooting to complete system upgrade'
      removes: /var/run/reboot-required
  - name: Copy Bitcoin service file
    template:
        src: btc.service
        dest: /etc/systemd/system
  - name: Clone Bitcoin git repo
    become_user: "{{ usr_name }}"
    git:
      repo: "https://github.com/bitcoin/bitcoin.git"
      dest: "~/bitcoin-latest"
    register: git_out
  - name: Stop running the old binary
    systemd:
      name: btc
      state: stopped
    when: git_out['changed']
  - name: Run script to build Bitcoin
    become_user: "{{ usr_name }}"
    script:
      chdir: "/home/{{ usr_name }}/"
      cmd: btc-build.sh "{{ usr_name }}"
    when: git_out['changed']
  - name: Start and enable bitcoin service
    systemd:
      name: btc
      state: started
      enabled: yes
