---
- name: Bootstrap Host and Install HAProxy
  hosts: proxy
  roles:
    - full-upgrade
    - personalize
    - add-user
  tasks:
    - name: Install apt packages
      apt:
        state: present
        pkg:
        - haproxy
        - curl #just for testing connections to localhost
        - rsyslog #until we have a centralized logging platform
    - name: Copy the main config file
      copy:
        src: haproxy.cfg
        dest: "/etc/haproxy/haproxy.cfg"
        #mode: "644"
        force: yes
    - name: Copy the logging config file
      copy:
        src: haproxy-log.conf
        dest: "/etc/rsyslog.d/haproxy-log.conf"
        #mode: "644"
        force: yes

- name: Generate Let's Encrypt Certificates
  hosts: proxy
  vars:
    # running the app
    certbot_testmode: true
    certbot_install_method: package
    certbot_create_standalone_stop_services:
      - haproxy
    # creating certs
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_admin_email: "{{ usr_email }}"
    certbot_certs: "{{ certs }}"
    # renewing certs
    certbot_auto_renew: true
    certbot_auto_renew_hour: "4"
    certbot_auto_renew_minute: "20"
  roles:
    - geerlingguy.certbot

- name: Use Sym Links so Let's Encrypt certificates Match HAProxy Naming Convention
  hosts: proxy
  tasks:
    - name: Create container directory for certs
      file:
        path: /etc/haproxy/certs/
        state: directory
    - name: Create symbolic links for intermediate certificate chains
      file:
        src: "/etc/letsencrypt/live/{{ item }}/fullchain.pem"
        dest: "/etc/haproxy/certs/{{ item }}"
        state: link
      loop: "{{ domains }}"

    - name: Create symbolic links for private key files
      file:
        src: "/etc/letsencrypt/live/{{ item }}/privkey.pem"
        dest: "/etc/haproxy/certs/{{ item }}.key"
        state: link
      loop: "{{ domains }}"

# this needs to run AFTER the sym links have been created
- name: Restart Services to Apply Changes
  hosts: proxy
  tasks:
    - name: The certbot role (sometimes) restarts haproxy service already. Give it a few seconds to fully start.
      wait_for:
        timeout: 20
    - name: Restart haproxy service
      systemd:
        name: haproxy
        state: restarted
        enabled: yes
    - name: Restart rsyslog service
      systemd:
        name: rsyslog
        state: restarted
        enabled: yes
