---
- name: Install Sample Web Services
  hosts: service1,service2
  become: yes
  roles:
    - full-upgrade
    - personalize
    - add-user
  tasks:
    - name: Install apt packages
      apt:
        state: present
        pkg:
        - nodejs
        - npm
