---
# based on https://docs.docker.com/engine/install/ubuntu/
- name: Install and configure docker
  hosts: docker
  become: yes
  # roles:
  #   - full-upgrade
  #   - personalize
  #   - add-user
  tasks:
  - name: Add an Apt signing key, uses whichever key is at the URL
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
  - name: Add specified repository into sources list
    apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
  - name: Install docker packages
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
