---
- name: Install the dotnet dev environment
  hosts: dotnet
  become: yes
  roles:
    - full-upgrade
    - personalize
    - add-user
    - ubuntu-gui
    - vs-code
  tasks:
  - name: Install extensions to VS Code #assumes user is already configured
    become_user: "{{ usr_name }}" # vscode threw errors if trying to do this with the ubuntu/root user
    command:
      cmd: code --install-extension ms-dotnettools.csharp
      #cmd: whoami
