---
# ⚠️ WARNING: Changes are wiped out when configuration is changed via the GUI
# It happens on a per-configuration basis. For example
# - Chainging a user PW wipes user ssh keys, but leaves NUT alone.
# - Changing NUT configuration wipes ALL NUT conf files, but leaves users alone.
# Ansible can be helpful for experimentation, but use the pfSense GUI to make permanent changes.
- name: UPS server configuration
  hosts: routers
  roles:
  - baremetal-bootstrap
  tasks:
  - name: Listen on MGMT IP
    lineinfile:
      path: /usr/local/etc/nut/upsd.conf
      line: "LISTEN {{ ups_server }} "
  - name: Insert/Update remote user configuration
    blockinfile:
      path: /usr/local/etc/nut/upsd.users
      block: |
        [{{ ups_user }}]
        password={{ ups_pw }}
        upsmon slave
