---
# based on https://jonatack.github.io/articles/how-to-compile-bitcoin-core-and-run-the-tests
- name: Install Bitcoin
  hosts: bitcoin
  become: yes
  tasks:
  - name: Install dependencies
    apt:
      pkg:
      - build-essential
      - libtool
      - autotools-dev
      - automake
      - pkg-config
      - bsdmainutils
      - python3
      - libssl-dev
      - libevent-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-chrono-dev
      - libboost-test-dev
      - libboost-thread-dev
      - libminiupnpc-dev
      - libzmq3-dev
      - libqt5gui5
      - libqt5core5a
      - libqt5dbus5
      - qttools5-dev
      - qttools5-dev-tools
      - libprotobuf-dev
      - protobuf-compiler
      - git
      - libsqlite3-dev
  - name: Reboot system if required.
    command:
      cmd: shutdown -r now 'Rebooting to complete system upgrade'
      removes: /var/run/reboot-required
  - name: Clone Bitcoin git repo
    become_user: vince
    git:
      repo: "https://github.com/bitcoin/bitcoin.git"
      dest: "~/bitcoin"
    register: git_out
  - name: Run script to install Bitcoin
    become_user: vince
    script:
      chdir: "/home/vince/bitcoin/"
      cmd: install-btc.sh
    when: git_out['changed']
