---
- name: Create Hyper-V VMs
  hosts: localhost
  tasks:
  # dotnet
  - name: Check if dotnet VHDX file exists
    stat:
      path: "{{ vhd_dir }}{{ vms['dotnet']['id'] }}-os.vhdx" 
    register: dotnet_vhdx
  - name: Create the dotnet VM
    include_role:
      name: provision-hyper-v
    vars:
      vm: "{{ vms['dotnet'] }}"
    when: not dotnet_vhdx.stat.exists
  # bitcoin
  - name: Check if bitcoin VHDX file exists
    stat:
      path: "{{ vhd_dir }}{{ vms['bitcoin']['id'] }}-os.vhdx" 
    register: bitcoin_vhdx
  - name: Create the bitcoin VM
    include_role:
      name: provision-hyper-v
    vars:
      vm: "{{ vms['bitcoin'] }}"
    when: not bitcoin_vhdx.stat.exists
