---
# based on https://github.com/paritytech/polkadot README
- name: Install Polkadot using the package manager
  hosts: polkadot
  become: yes
  roles:
    - full-upgrade
    - personalize
    - add-user
    - ubuntu-gui
  tasks:
  - name: Add an apt key by id from a keyserver
    apt_key:
      keyserver: hkps://keys.mailvelope.com
      id: 9D4B2B6EB8F97156D19669A9FF0812D491B96798
  - name: Add specified repository into sources list
    apt_repository:
      repo: deb https://releases.parity.io/deb release main
      state: present
  - name: Install dependencies
    apt:
      pkg:
      - parity-keyring
      - polkadot
      - python3-pip
      - python3-virtualenv
      - python3-setuptools
    register: apt_result
  - name: Install github python package
    pip:
      name: github3.py
  - name: Get latest release of Polkadot js-app
    github_release:
      user: polkadot-js
      repo: apps
      action: latest_release
    register: gh_release
  - name: Download front-end client #does not appear to re-download if the file already exists
    become_user: "{{ usr_name }}"
    get_url:
      # the replace filter is to change it from somethng like 'v0.98.1' to '0.98.1'
      url: "https://github.com/polkadot-js/apps/releases/download/{{ gh_release.tag }}/Polkadot-JS-Apps-{{ gh_release.tag | replace('v', '') }}.AppImage"
      dest: "~/"
      mode: "755"
  - name: Restart system if any packages were installed or upgraded
    reboot:
    when: apt_result['changed']
  - name: Set CLI flags
    lineinfile:
      path: /etc/default/polkadot
      regexp: '^POLKADOT_CLI_ARGS='
      line: POLKADOT_CLI_ARGS="--rpc-cors file:// --name '{{ node_name }}' --pruning archive""
    register: line_result
  - name: Restart polkadot service if config changes
    systemd:
      name: polkadot
      state: restarted
    when: apt_result['changed'] or line_result['changed']
  - name: Start and enable polkadot service
    systemd:
      name: polkadot
      state: started
      enabled: yes
