---
- name: Create Hyper-V VMs if they don't already exist
  hosts: ubuntu_cloud
  gather_facts: no # this will fail if the VMs don't exist yet
  vars:
    - srv_det: "{{ hostvars['hyper_v'] }}"
  tasks:
  - name: Check if VHDX file exists
    delegate_to: hyper_v
    stat:
      path: "{{ srv_det['vhd_dir'] }}{{ id }}-os.vhdx" 
    register: vhdx
  - name: Create the VM
    delegate_to: hyper_v
    import_role:
      name: provision-hyper-v
    when: not vhdx.stat.exists
