---
- name: Create VMs if they don't already exist
  hosts: pve5
  gather_facts: no # this will fail if the VMs don't exist yet
  vars:
    - img_url: "https://cloud.centos.org/altarch/7/images/"
    - img_file: "CentOS-7-x86_64-GenericCloud.qcow2"
    - tgt_storage: "quad-ssd"
  tasks:
  - name: Download cloud image #does not appear to re-download if client recently accessed (HTTP 304 Not Modified)
    get_url:
      url: "{{ img_url }}{{ img_file }}"
      dest: "~/{{ img_file }}"
  - name: Create new VM with minimal options
    # delegate_to: pve5
    proxmox_kvm:
      proxmox_default_behavior: no_defaults
      api_user: root@pam
      api_password: "{{ root_pw }}"
      api_host: 192.168.128.5
      node: pve5
      # hardware
      memory: 49152 #48 GiB
      cores: 20
      cpu: host
      net:
        net0: "virtio,bridge=vmbr1"
      ide:
        ide2: 'local:cloudinit,format=qcow2'
      # cloud-init
      sshkeys: "{{ pub_key }}"
      cipassword: easypass
      ipconfig:
        ipconfig0: 'ip=192.168.129.2/24,gw=192.168.129.1'
      # options
      name: robox0
      onboot: yes
      ostype: l26
      scsihw: virtio-scsi-pci
      agent: yes
    register: vm
  - name: Import template disk # NOT IDEMPOTENT !!
    command:
      cmd: "qm importdisk {{ vm.vmid }} ~/{{ img_file }} {{ tgt_storage }}"
  - name: Attach template disk to SCSI controller
    command:
      cmd: "qm set {{ vm.vmid }} --scsi0 {{ tgt_storage }}:{{ vm.vmid }}/vm-{{ vm.vmid }}-disk-0.raw"
  - name: Set disk as bootable
    command:
      cmd: "qm set {{ vm.vmid }} --boot order=scsi0"
