---
- name: Create VMs if they don't already exist
  hosts: pve5
  gather_facts: no # this will fail if the VMs don't exist yet
  vars:
    - img_url: "https://cloud-images.ubuntu.com/releases/hirsute/release/"
    - img_file: "ubuntu-21.04-server-cloudimg-amd64.img"
    - tgt_storage: "quad-ssd"
  tasks:
  - name: Download cloud image #does not appear to re-download if client recently accessed (HTTP 304 Not Modified)
    get_url:
      url: "{{ img_url }}{{ img_file }}"
      dest: "~/{{ img_file }}"
  - name: Create new VM with minimal options
    # delegate_to: pve5
    proxmox_kvm:
      proxmox_default_behavior: no_defaults
      api_user: root@pam
      api_password: "{{ root_pw }}"
      api_host: 192.168.128.5
      node: pve5
      # hardware
      memory: 2048
      cores: 1
      sockets: 1
      net:
        net0: "virtio,bridge=vmbr1"
      ide:
        ide2: 'local:cloudinit,format=qcow2'
        # ide2: 'none,media=cdrom'
      # cloud-init
      citype: nocloud
      cipassword: easypass
      ipconfig:
        ipconfig0: 'ip=192.168.129.2/24,gw=192.168.129.1'
      # options
      name: dev
      # onboot: yes
      ostype: l26
      scsihw: virtio-scsi-pci
      agent: yes
      #args: "-serial unix:/var/run/qemu-server/100.serial,server,nowait,-device virtio-rng-pci"
      # for iterative deleting
      # state: absent
    register: vm
  - name: Import template disk # NOT IDEMPOTENT !!
    command:
      cmd: "qm importdisk {{ vm.vmid }} ~/{{ img_file }} {{ tgt_storage }}"
  - name: Attach template disk to SCSI controller
    command:
      cmd: "qm set {{ vm.vmid }} --scsi0 {{ tgt_storage }}:{{ vm.vmid }}/vm-{{ vm.vmid }}-disk-0.raw"
  - name: Set disk as bootable
    command:
      cmd: "qm set {{ vm.vmid }} --boot order=scsi0"
