---
- name: Hello from Proxmox nodes
  hosts: proxmox_nodes
  gather_facts: no # this will fail if the VMs don't exist yet
  tasks:
  - name: Say hello
    debug:
      msg: "hi"
- name: Hello from Proxmox VMs
  hosts: proxmox_vms
  gather_facts: no # this will fail if the VMs don't exist yet
  tasks:
  - debug:
      var: tvar


- name: Hello from node2
  hosts: node2
  gather_facts: no # this will fail if the VMs don't exist yet
  tasks:
  - debug:
      var: virt_host

- name: Hello from all vms
  hosts: proxmox_vms
  gather_facts: no # this will fail if the VMs don't exist yet
  tasks:
  - debug:
      var: virt_host

  
- name: Node level stuff
  hosts: proxmox_vms
  gather_facts: no # this will fail if the VMs don't exist yet
  vars:
    virt_host_ip: "{{ hostvars[virt_host]['ansible_host'] }}"
  tasks:
  - command:
      cmd: echo hi
    delegate_to: "{{ virt_host }}"
  - debug:
      msg: "{{ api_user }} {{ virt_host_ip  }} {{ dmz_bridge }}"

- name: Host level stuff
  hosts: proxmox_vms
  gather_facts: no # this will fail if the VMs don't exist yet
  vars:
  tasks:
  - debug:
      msg: "{{ vcpus }} {{ ram }} {{ ansible_host }}/24,gw={{ dmz_gw }} {{ inventory_hostname }} {{ tgt_storage }}"