---
# scheme: 1 SSD with OS plus LVM thinpool, expanded by second drive that is dedicated LVM space.
- name: Partition disks and configure LVM on pve4
  hosts: pve4
  tasks:

  # Configure partitions
  # - name: Wipe all partitions
  #   command:
  #     cmd: "sgdisk {{ item }} --zap-all"
  #     removes: "{{ item }}1"
  #   loop: "{{ lvm_drives }}"
  - name: Create partitions
    command:
      cmd: "sgdisk {{ item }} --largest-new=1 --typecode=1:8e00 --change-name=1:'Linux LVM'"
      creates: "{{ item }}1"
    loop: "{{ lvm_drives }}"

  # Configure LVM
  # https://www.redhat.com/sysadmin/automating-logical-volume-manager
  - name: Associate /dev/sda1 with vg and resize maximum possible
    lvg:
      vg: pve
      pvs: "{{ lvm_parts | join(',') }}"
  - name: Create a logical volume with a pre-calculated size
    lvol:
      vg: pve
      lv: data
      size: "{{ data_space }}"
