---
- name: Do a lot of debug printing to see how complex variables move through tasks and roles.
  hosts: localhost
  roles:
  - { role: "print-vars", vm_id: 35 }
  - { role: "print-vars", vm_id: 36 }