---
- name: Do a lot of debug printing to see how complex variables move through tasks and roles.
  hosts: virt_servers
  roles:
  - { role: "print-vars", vm: "{{ vms['dotnet'] }}" }
  tasks:
  - name: print a group var
    debug:
      var: time_zone
  - name: print a host var
    debug:
      var: vhd_dir