---
- name: Bootstrap Host, Including GUI and IDE
  hosts: devenv
  become: yes
  roles:
    - full-upgrade
    - personalize
    - unprivileged-user
    - ubuntu-gui
    - vs-code
    - dotnet-sdk
    - private-key
  handlers:
    - import_tasks: handlers.yml
  tasks:

  - name: Configure Ansible PPA
    apt_repository:
      repo: 'ppa:ansible/ansible'
      state: present

  - name: Install apt Packages
    apt:
      state: present
      update_cache: yes # important
      pkg:
        - ansible
        - python3-pip

  - name: Disable Strict Host Key Checking
    lineinfile:
      path: /etc/ssh/ssh_config
      line: "StrictHostKeyChecking no"
      regexp: "StrictHostKeyChecking"
      state: present

  - name: Hard-Code Hosts on DMZ
    lineinfile:
      path: /etc/cloud/templates/hosts.debian.tmpl
      line: "192.168.129.30 {{ item }}"
      state: present
    loop: "{{ domains }}"
    notify:
    - Restart

- name: User Config - IDE Extensions, Python Packages, Ansible Roles, and Aliases
  hosts: devenv
  vars:
    ansible_user: "{{ usr_name }}"
  tasks:

  - name: Install extensions to VS Code
    command:
      cmd: |
        code --install-extension ms-dotnettools.csharp
        code --install-extension ionide.ionide-fsharp
        code --install-extension oderwat.indent-rainbow
      # cmd: whoami

  - name:  Copy Encrypted Vault PW File to VM
    copy:
      src: vault/vault_pw.txt
      dest: "~/.ansible/"
      mode: "664"

  - name: Install Certbot Role from Ansible Galaxy
    community.general.ansible_galaxy_install:
      type: role
      name: geerlingguy.certbot

  - name: Install Python Packages
    pip:
      name:
      - pexpect
      - proxmoxer

  - name: Add Alias to Run Ansible Playbook
    lineinfile:
      path: "~/.bashrc"
      line: 'alias vvans="ansible-playbook -i inventory/hosts.yml --vault-password-file ~/.ansible/vault_pw.txt"'
      state: present

  - name: Add Alias Show Git Log
    lineinfile:
      path: "~/.bashrc"
      line: 'alias vvlog="git log --all --oneline --graph"'
      state: present

  - name: Clone This Repository
    git:
      repo: 'https://github.com/VincentSaelzler/hyper-homelab.git'
      dest: "~/src/hyper-homelab/"
