---
- name: Install the VS Code dev environment
  hosts: devenv
  become: yes
  roles:
    - full-upgrade
    - personalize
    - add-user
    - ubuntu-gui
    - vs-code
    - private-key
  tasks:
  - name: Install extensions to VS Code #assumes user is already configured
    become_user: "{{ usr_name }}" # vscode threw errors if trying to do this with the ubuntu/root user
    command:
      cmd: |
        code --install-extension ms-dotnettools.csharp
        code --install-extension ionide.ionide-fsharp
        code --install-extension oderwat.indent-rainbow
      #cmd: whoami
  - name:  copy encrypted private ansible PW file to VM
    become_user: "{{ usr_name }}"
    copy:
      src: vault/vault_pw.txt
      dest: "~/.ansible/"
      mode: "664"
  - name: Configure Ansible PPA
    apt_repository:
      repo: 'ppa:ansible/ansible'
      state: present
  - name: Install apt packages
    apt:
      state: present
      update_cache: yes # important
      pkg:
        - ansible
        - python3-pip
  - name: Install python packages
    pip:
      name:
      - pexpect
      - proxmoxer
  - name: Disable strict host key checking
    lineinfile:
      path: /etc/ssh/ssh_config
      line: "StrictHostKeyChecking no"
      regexp: "StrictHostKeyChecking"
      state: present
  - name: Add alias to run ansible playbook
    lineinfile:
      path: "/home/{{ usr_name }}/.bashrc"
      line: 'alias vvans="ansible-playbook -i inventory/hosts.yml --vault-password-file ~/.ansible/vault_pw.txt"'
      state: present
