---
# Install apt Package(s)

- name: Install rsyslog
  apt:
    state: present
    pkg: rsyslog
  notify: Restart and Enable rsyslog

# Edits to the Main Configuration File /etc/rsyslog.conf

- name: Comment Out Kernel Module # doesn't seem to work in containers
  replace:
    path: /etc/rsyslog.conf
    regexp: '^module\(load="imklog"\)'
    replace: '#module(load="imklog")'
  when: is_container
  notify: Restart and Enable rsyslog

- name: Uncomment TCP Module
  replace:
    path: /etc/rsyslog.conf
    regexp: '^#module\(load="imtcp"\)'
    replace: 'module(load="imtcp")'
  when: is_log_server
  notify: Restart and Enable rsyslog

- name: Uncomment TCP Input Listener
  replace:
    path: /etc/rsyslog.conf
    regexp: '^#input\(type="imtcp" port="514"\)'
    replace: 'input(type="imtcp" port="514")'
  when: is_log_server
  notify: Restart and Enable rsyslog

# Additional Files in /etc/rsyslog.d/

- name: Copy Server Config File
  template:
    src: server.conf
    dest: /etc/rsyslog.d/save-tcp.conf
  when: is_log_server
  notify: Restart and Enable rsyslog

- name: Copy Client Config File
  template:
    src: client.conf
    dest: /etc/rsyslog.d/send-tcp.conf
  when: not is_log_server
  notify: Restart and Enable rsyslog
